consul:
  command: agent -server -bootstrap-expect=1  -node=node1 -client 0.0.0.0 -ui -bind=0.0.0.0 -join 127.0.0.2
  image: consul:latest
  hostname: "registry"
  ports:
    - "18300:8300"
    - "18400:8400"
    - "18500:8500"
    - "18600:53/udp"

route:
  command: --registry consul --registry_address=registry:8500 --register_interval=5 --register_ttl=10 web
  build: ./routeweb
  links:
    - consul
  ports:
    - "19999:9999"

test:
  #覆盖启动后的执行命令
  command: --registry consul --registry_address=registry:8500 --register_interval=5 --register_ttl=10 srv
  build: ./testsrv
  links:
    - consul