// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/MyWebSocket/MyWebSocket.proto

package go_micro_srv_MyWebSocket

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for MyWebSocket service

type MyWebSocketService interface {
	MyWebSocketCall(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (MyWebSocket_StreamService, error)
	PingPong(ctx context.Context, opts ...client.CallOption) (MyWebSocket_PingPongService, error)
}

type myWebSocketService struct {
	c    client.Client
	name string
}

func NewMyWebSocketService(name string, c client.Client) MyWebSocketService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "go.micro.srv.MyWebSocket"
	}
	return &myWebSocketService{
		c:    c,
		name: name,
	}
}

func (c *myWebSocketService) MyWebSocketCall(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "MyWebSocket.MyWebSocketCall", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *myWebSocketService) Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (MyWebSocket_StreamService, error) {
	req := c.c.NewRequest(c.name, "MyWebSocket.Stream", &StreamingRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &myWebSocketServiceStream{stream}, nil
}

type MyWebSocket_StreamService interface {
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*StreamingResponse, error)
}

type myWebSocketServiceStream struct {
	stream client.Stream
}

func (x *myWebSocketServiceStream) Close() error {
	return x.stream.Close()
}

func (x *myWebSocketServiceStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *myWebSocketServiceStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *myWebSocketServiceStream) Recv() (*StreamingResponse, error) {
	m := new(StreamingResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *myWebSocketService) PingPong(ctx context.Context, opts ...client.CallOption) (MyWebSocket_PingPongService, error) {
	req := c.c.NewRequest(c.name, "MyWebSocket.PingPong", &Ping{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &myWebSocketServicePingPong{stream}, nil
}

type MyWebSocket_PingPongService interface {
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Ping) error
	Recv() (*Pong, error)
}

type myWebSocketServicePingPong struct {
	stream client.Stream
}

func (x *myWebSocketServicePingPong) Close() error {
	return x.stream.Close()
}

func (x *myWebSocketServicePingPong) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *myWebSocketServicePingPong) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *myWebSocketServicePingPong) Send(m *Ping) error {
	return x.stream.Send(m)
}

func (x *myWebSocketServicePingPong) Recv() (*Pong, error) {
	m := new(Pong)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for MyWebSocket service

type MyWebSocketHandler interface {
	MyWebSocketCall(context.Context, *Request, *Response) error
	Stream(context.Context, *StreamingRequest, MyWebSocket_StreamStream) error
	PingPong(context.Context, MyWebSocket_PingPongStream) error
}

func RegisterMyWebSocketHandler(s server.Server, hdlr MyWebSocketHandler, opts ...server.HandlerOption) error {
	type myWebSocket interface {
		MyWebSocketCall(ctx context.Context, in *Request, out *Response) error
		Stream(ctx context.Context, stream server.Stream) error
		PingPong(ctx context.Context, stream server.Stream) error
	}
	type MyWebSocket struct {
		myWebSocket
	}
	h := &myWebSocketHandler{hdlr}
	return s.Handle(s.NewHandler(&MyWebSocket{h}, opts...))
}

type myWebSocketHandler struct {
	MyWebSocketHandler
}

func (h *myWebSocketHandler) MyWebSocketCall(ctx context.Context, in *Request, out *Response) error {
	return h.MyWebSocketHandler.MyWebSocketCall(ctx, in, out)
}

func (h *myWebSocketHandler) Stream(ctx context.Context, stream server.Stream) error {
	m := new(StreamingRequest)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.MyWebSocketHandler.Stream(ctx, m, &myWebSocketStreamStream{stream})
}

type MyWebSocket_StreamStream interface {
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*StreamingResponse) error
}

type myWebSocketStreamStream struct {
	stream server.Stream
}

func (x *myWebSocketStreamStream) Close() error {
	return x.stream.Close()
}

func (x *myWebSocketStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *myWebSocketStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *myWebSocketStreamStream) Send(m *StreamingResponse) error {
	return x.stream.Send(m)
}

func (h *myWebSocketHandler) PingPong(ctx context.Context, stream server.Stream) error {
	return h.MyWebSocketHandler.PingPong(ctx, &myWebSocketPingPongStream{stream})
}

type MyWebSocket_PingPongStream interface {
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Pong) error
	Recv() (*Ping, error)
}

type myWebSocketPingPongStream struct {
	stream server.Stream
}

func (x *myWebSocketPingPongStream) Close() error {
	return x.stream.Close()
}

func (x *myWebSocketPingPongStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *myWebSocketPingPongStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *myWebSocketPingPongStream) Send(m *Pong) error {
	return x.stream.Send(m)
}

func (x *myWebSocketPingPongStream) Recv() (*Ping, error) {
	m := new(Ping)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}
